#!/usr/bin/env python3
"""Post-freeze audit of the preregistered group-weighted inner-split objective."""
import hashlib,json
import numpy as np,pandas as pd
from gate2e1_common import ROOT,PRIMARY,config,load_protocol,write_json
def key(x):return hashlib.sha256(f'20260721|{x}'.encode()).hexdigest()
def main():
 c=config();results={}
 for protocol,spec in c['protocols'].items():
  frame,_,_=load_protocol(protocol,False);unit=spec['inner_unit'];current=pd.read_parquet(ROOT/c['local_root']/'inner_splits'/f'{protocol}_inner_split.parquet')
  units=frame.groupby(unit).apply(lambda q:np.sum(q[PRIMARY]*q.group_weight)/np.sum(q.group_weight),include_groups=False).rename('target').reset_index();units['bin']=pd.qcut(units.target.rank(method='first'),q=min(c['inner_split']['primary_quantile_bins'],len(units)),labels=False);forced=set(frame.loc[frame.historical_status.eq('HISTORICAL_TRAIN_OVERLAP'),unit]);checkpoint=set()
  for _,block in units.groupby('bin'):
   eligible=sorted([x for x in block[unit] if x not in forced],key=key);checkpoint.update(eligible[:max(1,int(round(len(eligible)*c['inner_split']['checkpoint_fraction'])))])
  expected=set(frame.loc[frame[unit].isin(checkpoint),'molecule_id']);actual=set(current.loc[current.inner_partition.eq('inner_checkpoint'),'molecule_id']);results[protocol]={'current_checkpoint_records':len(actual),'correct_group_weighted_checkpoint_records':len(expected),'symmetric_difference_records':len(actual^expected),'current_only':len(actual-expected),'correct_only':len(expected-actual),'assignment_identical':actual==expected}
 correction={'status':'BLOCKED_MULTITASK_PIPELINE_INTEGRITY','detected_after_official_validation_unlock':True,'root_cause':'Inner-unit quantile target used unweighted record mean instead of preregistered structure-group-weighted mean.','protocols':results,'scientific_contract_changed':False,'rerun_permitted':False,'reason_no_rerun':'Official validation has already been observed; correcting and retraining v1 would be post-validation protocol repair.','existing_metrics_status':'DIAGNOSTIC_ONLY_NOT_ADMISSION_EVIDENCE','test_accessed':False,'final673_accessed':False};write_json('data_registry/gate2e1_postfreeze_integrity_correction_v1.json',correction)
 evidence=json.loads((ROOT/'logs/gate2e1_evidence.json').read_text());evidence.update({'status':'BLOCKED_MULTITASK_PIPELINE_INTEGRITY','scientific_decision':'INVALIDATED_BY_INNER_SPLIT_WEIGHTING_VIOLATION','masked_decision':'INVALIDATED_BY_INNER_SPLIT_WEIGHTING_VIOLATION','postfreeze_integrity_correction':'data_registry/gate2e1_postfreeze_integrity_correction_v1.json','rerun_performed':False});write_json('logs/gate2e1_evidence.json',evidence)
 report=f"# Gate 2-E1 post-freeze integrity correction\n\nFinal status: `BLOCKED_MULTITASK_PIPELINE_INTEGRITY`.\n\nThe preregistration required primary-quantile balance based on structure-group weights. The implemented inner-unit target used an unweighted record mean. IID is unaffected because each atomic unit is one structure group. Acceptor-cold is affected: the frozen checkpoint set has {results['acceptor_cold']['current_checkpoint_records']} records, the correct weighted reconstruction has {results['acceptor_cold']['correct_group_weighted_checkpoint_records']}, and {results['acceptor_cold']['symmetric_difference_records']} records change assignment.\n\nThis was detected only after official validation had been consumed. Therefore v1 cannot be repaired by retraining: such a rerun would be informed by observed validation results. The 18 models and reported metrics remain preserved as diagnostic artifacts, but `MULTITASK_SIGNAL_INCONCLUSIVE` and the masked decision are invalidated as admission conclusions. No rerun, test access, or tag rewrite occurred. A future experiment requires a new preregistration and an unobserved evaluation boundary.\n";(ROOT/'reports/gate2e1_postfreeze_integrity_correction.md').write_text(report);(ROOT/'reports/gate2e1_final_decision.md').write_text("# Gate 2-E1 final decision\n\n## `BLOCKED_MULTITASK_PIPELINE_INTEGRITY`\n\nThe acceptor-cold inner split violated the preregistered group-weighted quantile objective. Because this was discovered after official validation unlock, the run cannot be repaired or rerun within v1. Existing metrics are diagnostic only and do not support multitask admission or rejection. See `gate2e1_postfreeze_integrity_correction.md`.\n")
 print(json.dumps(correction,indent=2))
if __name__=='__main__':main()
